### ISSUE TITLE
spawn farp inside deployzone

### ISSUE THREAD

**Issue by vinchantenl** [drienties/DCS-Arena#13]

**Comment by drienties** [comment]
Kun je die wat verder beschrijven? snap niet geheel wat je hiermee wilt

**Comment by vinchantenl** [comment]
eigenlijk mogen ze de FARP overal in de deployzone laten spawnen (als dat al werkt)

**Comment by drienties** [comment]
even gekeken naar je zones, maar in theorie( als ik het random maak) kan de farp ook aan de compleet verkeerde kant spawnen dan.

**Comment by vinchantenl** [comment]
gisteren al besproken maar ze dus niet random spawnen maar kijken of het lukt om ze met een marker op een specifieke plek te zetten en dan kunnen er alleen geen heli's er spawnen. Die zouden dan vanaf de bases moeten beginnen en zullen ze er eerst heen moeten vliegen. En als dit niet lukt dan kunnen we handmatig farps neerzetten halverwege de basis en frontlinie en daar wel spawnable helo's neerzetten

**Comment by drienties** [comment]
unit slots kunnen niet dynamisch worden gespawned, bemande FARPS moeten handmatig worden aangemaakt.
