### ISSUE TITLE
spawnen van samlr en samsr (en waarschijnlijk sampd) werkt niet

### ISSUE THREAD

**Issue by vinchantenl** [drienties/DCS-Arena#19]
underscore eruit halen?

**Comment by drienties** [comment]
al gezien, jou miz file heeft idd nog de _ tussen sam en sr/lr staan. als je die eruit haalt is het gefixed

**Comment by drienties** [comment]
issue kan gesloten worden, code is zoals besproken. template name in miz file aanpassen
